"""
Django settings for geoportal_backend project.

Generated by 'django-admin startproject' using Django.
For more information on this file, see
https://docs.djangoproject.com/en/stable/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/stable/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/stable/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here'  # Replace in production

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # GeoDjango
    'rest_framework',      # Django REST Framework
    'rest_framework_gis',  # DRF GIS
    'corsheaders',         # Django CORS Headers
    'geoinfo.apps.GeoinfoConfig', # Nuestra aplicación
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # CORS Middleware (idealmente antes de CommonMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geoportal_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geoportal_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/stable/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'geoportal_db',  # Nombre de tu base de datos PostGIS
        'USER': 'your_db_user',    # Usuario de la base de datos
        'PASSWORD': 'your_db_password', # Contraseña
        'HOST': 'localhost',     # O la IP/hostname de tu servidor de BD
        'PORT': '5432',          # Puerto por defecto de PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/stable/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/stable/topics/i18n/

LANGUAGE_CODE = 'es-es' # Código de lenguaje, ej. Español de España

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/stable/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/stable/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        # Podrías añadir JWTAuthentication aquí si lo usas
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer', # Para la API navegable
    ),
    # Necesario para que DRF-GIS funcione correctamente con GeoJSON
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework_gis.parsers.GeoJSONParser',
    )
}

# GDAL_LIBRARY_PATH y GEOS_LIBRARY_PATH
# Usualmente GeoDjango puede encontrarlos automáticamente si están en el PATH del sistema.
# Si tienes problemas, puedes especificarlos aquí.
# Ejemplo:
# GDAL_LIBRARY_PATH = '/usr/local/lib/libgdal.so'
# GEOS_LIBRARY_PATH = '/usr/local/lib/libgeos_c.so'

# SRID por defecto para geometrías (WGS84)
# Es buena práctica definirlo, aunque GeoDjango usa 4326 por defecto para muchos campos.
SRID = 4326

# Media files (para los Documentos Adjuntos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuración para perfiles de usuario personalizados si se extiende el modelo User
# AUTH_USER_MODEL = 'geoinfo.CustomUser' # Ejemplo, si creas un CustomUser en la app geoinfo

# Logging (opcional, pero bueno para producción)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO', # Cambiar a DEBUG para más detalle
    },
}

# CORS Configuration
# Para desarrollo, podemos permitir todos los orígenes.
# En producción, se debería restringir a los dominios del frontend.
CORS_ALLOW_ALL_ORIGINS = True
# O, para ser más específico:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000", # Ejemplo si el frontend corre en el puerto 3000
#     "http://127.0.0.1:3000",
#     "http://localhost:5500", # Puerto común para Live Server de VSCode para archivos HTML
#     "http://127.0.0.1:5500",
#     # Añadir el dominio de producción del frontend aquí
# ]

# Si necesitas permitir credenciales (cookies, etc.) con CORS:
# CORS_ALLOW_CREDENTIALS = True

# También puedes configurar CORS_ALLOWED_METHODS, CORS_ALLOWED_HEADERS, etc.
# Por ahora, CORS_ALLOW_ALL_ORIGINS = True es lo más simple para desarrollo local.
